#ifndef CLIENT_CONFIG_H
#define CLIENT_CONFIG_H

#define MAX_CLIENTS 4
#define MAX_BEASTS 10
#define TREASURES_AMOUNT 50
#define BUSHES_AMOUNT 120
#define MAP_HEIGHT 28
#define MAP_WIDTH 86
#define TURN_TIME 300000
#define PLAYER_POV 15
#define INFO_POS_Y (MAP_HEIGHT + 2)
#define INFO_POS_X 5
#define CLIENT_INFO_POS_Y (PLAYER_POV + 5)
#define CLIENT_INFO_POS_X 5
#define MAP_FILENAME "map_small.txt"

#endif //CLIENT_CONFIG_H
